### ISSUE TITLE
ZRANGEBYSCORE min/max argument types not complete

### ISSUE THREAD

**Issue by mmkal** [redis/redis-doc#1420]
In `commands.json`, ZRANGEBYSCORE has it's `min` and `max` arguments as `double`: https://github.com/redis/redis-doc/blob/e978cf5875a257ba4a3389abfa844a23df28c0f0/commands.json#L3806-L3813

But the value is also allowed to be `+inf`, `-inf`, `(1` etc.

Likewise with ZREMRANGEBYSCORE, ZREVRANGEBYSCORE and ZCOUNT.

It'd be great if commands.json could somehow indicate that more than just `double` is allowed.

Note that https://github.com/redis/redis-doc/pull/1232 would solve this problem with no extra effort, because this is already possible to express precisely json schema:

```yaml
name: min
schema:
  anyOf:
  - type: number
  - type: string
    enum: [-inf, +inf]
  - type: string
    pattern: ^\(\d+$
```

Related: https://github.com/mmkal/handy-redis/issues/30
